x = np.linspace(1, 10, 10) 
y = np.random.rand(10, 10) 
plt.plot(x, y[0]) 
plt.plot(x, y[1]) 
plt.plot(x, y[2])
plt.plot(x, y[3]) 
plt.plot(x, y[4]) 
plt.plot(x, y[5]) 
plt.plot(x, y[6])
plt.plot(x, y[7]) 
plt.plot(x, y[8]) 
plt.plot(x, y[9]) 
plt.show()